version: '2'

services:
  slides:
    image: hairyhenderson/remarkjs
    volumes:
      - ./Notes.md:/slides.md
    environment:
      - TITLE=Docker Bench for Security
      - HIGHLIGHT_LINES=true
      - HIGHLIGHT_SPANS=true
      - RATIO=16:9
    ports:
      - 8080:80
