resources:
- name: resource
  type: git
  source:
    branch: master
    uri: https://github.com/arbourd/audition
    token: ((token))
- name: resource-image
  type: docker-image
  source:
    repository: arbourd/audition
    username: ((username))
    password: ((password))

jobs:
- name: Run-automatically
  plan:
  - get: resource
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: sh
        args:
        - -exc
        - |
          echo "I am the only test."

- name: Manually-trigger-me
  plan:
  - get: resource
    passed:
      - Run-automatically
    trigger: false
  - put: resource-image
    params: {build: resource}
