version: '2.0'

services:
  slides:
    restart: always
    image: hairyhenderson/remarkjs
    volumes:
      - ./slides.md:/slides.md
      - ./slides.md:/usr/share/nginx/html/slides.md
      - ./images:/usr/share/nginx/html/images
    environment:
      - DEV_MODE=true
      - TITLE=Prometheus on Docker for AWS
      - HIGHLIGHT_LINES=true
      - HIGHLIGHT_SPANS=true
      - RATIO=16:9
    ports:
      - 8080:80
