// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "WorstSocialNetwork": public TestHelpers
//
// Command:
// $ goagen
// --design=github.com/hairyhenderson/restdemo/design
// --out=$(GOPATH)/src/github.com/hairyhenderson/restdemo
// --version=v1.2.0-dirty

package test
