version: '2.0'

services:
  slides:
    image: hairyhenderson/remarkjs
    volumes:
      # - ./slides.md:/slides.md
      - ./index.html.tmpl:/index.html.tmpl
      - ./slides.md:/usr/share/nginx/html/slides.md
    environment:
      - DEV_MODE=true
      - TITLE=Docker Ottawa Meetup
      - HIGHLIGHT_LINES=true
      - HIGHLIGHT_SPANS=true
      - RATIO=16:9
    ports:
      - 8080:80
