// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "WorstSocialNetwork": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/hairyhenderson/restdemo/design
// --out=$(GOPATH)/src/github.com/hairyhenderson/restdemo
// --version=v1.2.0-dirty

package app

import (
	"fmt"
	"strings"
)

// HealthHref returns the resource href.
func HealthHref() string {
	return "/health"
}

// PostHref returns the resource href.
func PostHref(postID interface{}) string {
	parampostID := strings.TrimLeftFunc(fmt.Sprintf("%v", postID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/posts/%v", parampostID)
}
